#!/usr/bin/env zsh

export GPG_TTY=$(tty)

. "$ZDOTDIR/zinit.zsh"

# file matching
setopt EXTENDED_GLOB
setopt NOMATCH

# report status of background
setopt NOTIFY

# set vi mode
bindkey -v

# enable completions
autoload -Uz compinit && compinit

# add arrow keys
zstyle ':completion:*' menu select

# add vi keys to menu select
zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'l' vi-forward-char

# completions in privileged commands
zstyle ':completion::complete:*' gain-privileges 1

# enable carapace completions
zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'
source <(carapace _carapace)

. "$ZDOTDIR/history.zsh"

. "$ZDOTDIR/deattach.sh"
. "$ZDOTDIR/eza-tree.sh"
. "$ZDOTDIR/venv.sh"
. "$ZDOTDIR/up.sh"
. "$ZDOTDIR/proxy.sh"

. "$ZDOTDIR/oh-my-posh.zsh"
. "$ZDOTDIR/yazi.zsh"
. "$ZDOTDIR/fzf.zsh"
. "$ZDOTDIR/zoxide.zsh"

. "$ZDOTDIR/aliases.sh"
