#!/bin/env sh

# eza (ls)
alias ls='eza'
alias ll='eza -l'

# grep
alias grep='grep --color=auto'

# waybar
alias waybar-toggle='killall -SIGUSR1 waybar'
alias waybar-reload='killall -SIGUSR2 waybar'

# pacman
alias pacman='pacman --color=auto'

# neovim
alias vim='nvim'

# sudo
alias sudo='sudo '
# blank space is a hack

# fastfetch
alias ff='fastfetch'

# chezmoi
alias cz='chezmoi'

# bat
alias cat='bat --paging=never'

# git
alias g='git'

# helix
alias hx='helix'

# envs
alias e="$EDITOR"
alias v="$VISUAL"
