#!/bin/env sh

# eza

# grid
alias l='eza'
alias la='eza -a'

# long
alias ll='eza -l'
alias lla='eza -la'

# tree
alias lt='eza -T'
alias lta='eza -Ta'
alias ltl='eza_tree'


# grep
alias grep='grep --color=auto'

# waybar
alias waybar-toggle='killall -SIGUSR1 waybar'
alias waybar-reload='killall -SIGUSR2 waybar'

# pacman
alias pacman='pacman --color=auto'

# neovim
alias vim='nvim'

# sudo
alias sudo='sudo '
# blank space is a hack

# fastfetch
alias ff='fastfetch'

# chezmoi
alias cz='chezmoi'
alias czj='chezmoi cd'
alias cza='chezmoi apply'

# bat
alias cat='bat --paging=never'

# git
alias g='git'
alias ga='git add'
alias gs='git status'
alias gd='git diff'
alias gl='git log'
alias gc='git commit'
alias gp='git push'

# helix
alias hx='helix'

# envs
alias e="$EDITOR"
alias v="$VISUAL"

