#!/bin/env sh

# xdg user directories
# source: https://wiki.archlinux.org/title/XDG_Base_Directory#User_directories 
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# default programs
# source: https://wiki.archlinux.org/title/Environment_variables#Default_programs
export EDITOR="nvim"
export VISUAL="code"
export BROWSER="firefox"

# gpg
# source: https://wiki.archlinux.org/title/GnuPG#Configure_pinentry_to_use_the_correct_TTY
export GPG_TTY=$(tty)

# zsh config directory
# source: https://wiki.archlinux.org/title/Zsh#Startup/Shutdown_files
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

