#!/bin/env sh

# aliases
source "$ZDOTDIR/aliases"

# history
source "$ZDOTDIR/history"

setopt extendedglob nomatch notify
bindkey -v

# The following lines were added by compinstall
zstyle :compinstall filename '/home/d/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# plugins
source ~/.config/zsh/zsh-autocomplete/zsh-autocomplete.plugin.zsh 
source ~/.config/zsh/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

# prompt
PROMPT="%# %2~ > "

# zoxide
eval "$(zoxide init --cmd cd zsh)"

# fzf
eval "$(fzf --zsh)"

