#!/bin/env zsh

# enable powerlevel10k instant prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"

# source theme (powerlevel10k)
# source: https://github.com/romkatv/powerlevel10k
# source "$ZDOTDIR/theme/powerlevel10k/powerlevel10k.zsh-theme"
zinit ice depth"1"
zinit light romkatv/powerlevel10k

# source other files
source "$ZDOTDIR/aliases"
source "$ZDOTDIR/history"
source "$ZDOTDIR/plugins"

# file matching
setopt EXTENDED_GLOB
setopt NOMATCH

# report status of background
setopt NOTIFY

# set vi mode
bindkey -v

# if not running interactively, don't do anything
[[ $- != *i* ]] && return

# zoxide
eval "$(zoxide init --cmd cd zsh)"

# fzf
eval "$(fzf --zsh)"

# gpg
# source: https://wiki.archlinux.org/title/GnuPG#Configure_pinentry_to_use_the_correct_TTY
export GPG_TTY=$(tty)

# load powerlevek10k config
[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh
