#!/bin/env sh

# ls
alias ls='eza'

# grep
alias grep='grep --color=auto'

# waybar
alias waybar-toggle='killall -SIGUSR1 waybar'
alias waybar-reload='killall -SIGUSR2 waybar'

# pacman
alias pacman='pacman --color=auto'

# neovim
alias vim='nvim'
alias v='nvim'

# sudo
alias sudo='sudo '

# fastfetch
alias ff='fastfetch'

# chezmoi
alias cz='chezmoi'

# bat
alias cat='bat --paging=never'

