#!/bin/env zsh

ZSHRC="$ZDOTDIR/zshrc"

# enable oh-my-posh
# source: https://ohmyposh.dev/docs/installation/prompt
eval "$(oh-my-posh init zsh --config $OMP_CONFIG_HOME/zen.toml)"

# source other files
source "$ZSHRC/env"
source "$ZSHRC/aliases"
source "$ZSHRC/history"
source "$ZSHRC/zinit"
source "$ZSHRC/yazi"

# file matching
setopt EXTENDED_GLOB
setopt NOMATCH

# report status of background
setopt NOTIFY

# set vi mode
bindkey -v

# enable completions
autoload -Uz compinit && compinit

# fzf
eval "$(fzf --zsh)"

# zoxide
eval "$(zoxide init --cmd j zsh)"
