#!/usr/bin/env zsh

. "$ZDOTDIR/zinit.zsh"
. "$ZDOTDIR/options.zsh"
. "$ZDOTDIR/completions.zsh"
. "$ZDOTDIR/history.zsh"

. "$ZDOTDIR/deattach.sh"
. "$ZDOTDIR/eza-tree.sh"
. "$ZDOTDIR/venv.sh"
. "$ZDOTDIR/up.sh"

. "$ZDOTDIR/oh-my-posh.zsh"
. "$ZDOTDIR/yazi.zsh"
. "$ZDOTDIR/fzf.zsh"
. "$ZDOTDIR/zoxide.zsh"

. "$ZDOTDIR/aliases.sh"
