#!/bin/env zsh

export ZSH_RC="$ZDOTDIR/rc"

# file matching
setopt EXTENDED_GLOB
setopt NOMATCH

# report status of background
setopt NOTIFY

# set vi mode
bindkey -v

. "$ZSH_RC/zinit.zsh"
. "$ZSH_RC/aliases.sh"
. "$ZSH_RC/completion.zsh"
. "$ZSH_RC/history.zsh"
. "$ZSH_RC/path.zsh"

. "$ZDOTDIR/functions.sh"
. "$ZDOTDIR/programs.sh"
