#!/bin/env zsh

# enable plugins with zinit
# sources in order:
# https://github.com/zdharma-continuum/fast-syntax-highlighting
# https://github.com/zsh-users/zsh-autosuggestions
# https://github.com/marlonrichert/zsh-autocomplete
zinit depth"1" lucid light-mode for \
    wait atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" \
        zdharma-continuum/fast-syntax-highlighting \
    wait zsh-users/zsh-autosuggestions \
    marlonrichert/zsh-autocomplete

