hosts:
    kaede:
        outputs:
            "HDMI-A-1":
                width: 1920
                height: 1080
                hz: 144
    yuki:
        outputs:
            "eDP-1":
                width: 1920
                height: 1080
                hz: 60
